HAWKS_FULL_NAME = "Atlanta Hawks"
HAWKS_ABBREVIATION = "ATL"
CELTICS_FULL_NAME = "Boston Celtics"
CELTICS_ABBREVIATION = "BOS"
NETS_FULL_NAME = "Brooklyn Nets"
NETS_ABBREVIATION = "BKN"
HORNETS_FULL_NAME = "Charlotte Hornets"
HORNETS_ABBREVIATION = "CHA"
BULLS_FULL_NAME = "Chicago Bulls"
BULLS_ABBREVIATION = "CHI"
CAVALIERS_FULL_NAME = "Cleveland Cavaliers"
CAVALIERS_ABBREVIATION = "CLE"
MAVERICKS_FULL_NAME = "Dallas Mavericks"
MAVERICKS_ABBREVIATION = "DAL"
NUGGETS_FULL_NAME = "Denver Nuggets"
NUGGETS_ABBREVIATION = "DEN"
PISTONS_FULL_NAME = "Detroit Pistons"
PISTONS_ABBREVIATION = "DET"
WARRIORS_FULL_NAME = "Golden State Warriors"
WARRIORS_ABBREVIATION = "GSW"
ROCKETS_FULL_NAME = "Houston Rockets"
ROCKETS_ABBREVIATION = "HOU"
PACERS_FULL_NAME = "Indiana Pacers"
PACERS_ABBREVIATION = "IND"
CLIPPERS_FULL_NAME = "LA Clippers"
CLIPPERS_ABBREVIATION = "LAC"
LAKERS_FULL_NAME = "Los Angeles Lakers"
LAKERS_ABBREVIATION = "LAL"
GRIZZLIES_FULL_NAME = "Memphis Grizzlies"
GRIZZLIES_ABBREVIATION = "MEM"
HEAT_FULL_NAME = "Miami Heat"
HEAT_ABBREVIATION = "MIA"
BUCKS_FULL_NAME = "Milwaukee Bucks"
BUCKS_ABBREVIATION = "MIL"
TIMBERWOLVES_FULL_NAME = "Minnesota Timberwolves"
TIMBERWOLVES_ABBREVIATION = "MIN"
PELICANS_FULL_NAME = "New Orleans Pelicans"
PELICANS_ABBREVIATION = "NOP"
KNICKS_FULL_NAME = "New York Knicks"
KNICKS_ABBREVIATION = "NYK"
THUNDER_FULL_NAME = "Oklahoma City Thunder"
THUNDER_ABBREVIATION = "OKC"
MAGIC_FULL_NAME = "Orlando Magic"
MAGIC_ABBREVIATION = "ORL"
SIXERS_FULL_NAME = "Philadelphia 76ers"
SIXERS_ABBREVIATION = "PHI"
SUNS_FULL_NAME = "Phoenix Suns"
SUNS_ABBREVIATION = "PHX"
BLAZERS_FULL_NAME = "Portland Trail Blazers"
BLAZERS_ABBREVIATION = "POR"
KINGS_FULL_NAME = "Sacramento Kings"
KINGS_ABBREVIATION = "SAC"
SPURS_FULL_NAME = "San Antonio Spurs"
SPURS_ABBREVIATION = "SAS"
RAPTORS_FULL_NAME = "Toronto Raptors"
RAPTORS_ABBREVIATION = "TOR"
JAZZ_FULL_NAME = "Utah Jazz"
JAZZ_ABBREVIATION = "UTA"
WIZARDS_FULL_NAME = "Washington Wizards"
WIZARDS_ABBREVIATION = "WAS"


TEAM_FULL_NAMES = [
    HAWKS_FULL_NAME,
    CELTICS_FULL_NAME,
    NETS_FULL_NAME,
    HORNETS_FULL_NAME,
    BULLS_FULL_NAME,
    CAVALIERS_FULL_NAME,
    MAVERICKS_FULL_NAME,
    NUGGETS_FULL_NAME,
    PISTONS_FULL_NAME,
    WARRIORS_FULL_NAME,
    ROCKETS_FULL_NAME,
    PACERS_FULL_NAME,
    CLIPPERS_FULL_NAME,
    LAKERS_FULL_NAME,
    GRIZZLIES_FULL_NAME,
    HEAT_FULL_NAME,
    BUCKS_FULL_NAME,
    TIMBERWOLVES_FULL_NAME,
    PELICANS_FULL_NAME,
    KNICKS_FULL_NAME,
    THUNDER_FULL_NAME,
    MAGIC_FULL_NAME,
    SIXERS_FULL_NAME,
    SUNS_FULL_NAME,
    BLAZERS_FULL_NAME,
    KINGS_FULL_NAME,
    SPURS_FULL_NAME,
    RAPTORS_FULL_NAME,
    JAZZ_FULL_NAME,
    WIZARDS_FULL_NAME
]

TEAM_ABBREVIATIONS = [
    HAWKS_ABBREVIATION,
    CELTICS_ABBREVIATION,
    NETS_ABBREVIATION,
    HORNETS_ABBREVIATION,
    BULLS_ABBREVIATION,
    CAVALIERS_ABBREVIATION,
    MAVERICKS_ABBREVIATION,
    NUGGETS_ABBREVIATION,
    PISTONS_ABBREVIATION,
    WARRIORS_ABBREVIATION,
    ROCKETS_ABBREVIATION,
    PACERS_ABBREVIATION,
    CLIPPERS_ABBREVIATION,
    LAKERS_ABBREVIATION,
    GRIZZLIES_ABBREVIATION,
    HEAT_ABBREVIATION,
    BUCKS_ABBREVIATION,
    TIMBERWOLVES_ABBREVIATION,
    PELICANS_ABBREVIATION,
    KNICKS_ABBREVIATION,
    THUNDER_ABBREVIATION,
    MAGIC_ABBREVIATION,
    SIXERS_ABBREVIATION,
    SUNS_ABBREVIATION,
    BLAZERS_ABBREVIATION,
    KINGS_ABBREVIATION, 
    SPURS_ABBREVIATION,
    RAPTORS_ABBREVIATION,
    JAZZ_ABBREVIATION,
    WIZARDS_ABBREVIATION
]

TEAM_FULL_NAMES_LOOKUP = {
    HAWKS_ABBREVIATION: HAWKS_FULL_NAME,
    CELTICS_ABBREVIATION: CELTICS_FULL_NAME,
    NETS_ABBREVIATION: NETS_FULL_NAME,
    HORNETS_ABBREVIATION: HORNETS_FULL_NAME,
    BULLS_ABBREVIATION: BULLS_FULL_NAME,
    CAVALIERS_ABBREVIATION: CAVALIERS_FULL_NAME,
    MAVERICKS_ABBREVIATION: MAVERICKS_FULL_NAME,
    NUGGETS_ABBREVIATION: NUGGETS_FULL_NAME,
    PISTONS_ABBREVIATION: PISTONS_FULL_NAME,
    WARRIORS_ABBREVIATION: WARRIORS_FULL_NAME,
    ROCKETS_ABBREVIATION: ROCKETS_FULL_NAME,
    PACERS_ABBREVIATION: PACERS_FULL_NAME,
    CLIPPERS_ABBREVIATION: CLIPPERS_FULL_NAME,
    LAKERS_ABBREVIATION: LAKERS_FULL_NAME,
    GRIZZLIES_ABBREVIATION: GRIZZLIES_FULL_NAME,
    HEAT_ABBREVIATION: HEAT_FULL_NAME,
    BUCKS_ABBREVIATION: BUCKS_FULL_NAME,
    TIMBERWOLVES_ABBREVIATION: TIMBERWOLVES_FULL_NAME,
    PELICANS_ABBREVIATION: PELICANS_FULL_NAME,
    KNICKS_ABBREVIATION: KNICKS_FULL_NAME,
    THUNDER_ABBREVIATION: THUNDER_FULL_NAME,
    MAGIC_ABBREVIATION: MAGIC_FULL_NAME,
    SIXERS_ABBREVIATION: SIXERS_FULL_NAME,
    SUNS_ABBREVIATION: SUNS_FULL_NAME,
    BLAZERS_ABBREVIATION: BLAZERS_FULL_NAME,
    KINGS_ABBREVIATION: KINGS_FULL_NAME,
    SPURS_ABBREVIATION: SPURS_FULL_NAME,
    RAPTORS_ABBREVIATION: RAPTORS_FULL_NAME,
    JAZZ_ABBREVIATION: JAZZ_FULL_NAME,
    WIZARDS_ABBREVIATION: WIZARDS_FULL_NAME
}

TEAM_ABBREVIATIONS_LOOKUP = {
    HAWKS_FULL_NAME: HAWKS_ABBREVIATION,
    CELTICS_FULL_NAME: CELTICS_ABBREVIATION,
    NETS_FULL_NAME: NETS_ABBREVIATION,
    HORNETS_FULL_NAME: HORNETS_ABBREVIATION,
    BULLS_FULL_NAME: BULLS_ABBREVIATION,
    CAVALIERS_FULL_NAME: CAVALIERS_ABBREVIATION,
    MAVERICKS_FULL_NAME: MAVERICKS_ABBREVIATION,
    NUGGETS_FULL_NAME: NUGGETS_ABBREVIATION,
    PISTONS_FULL_NAME: PISTONS_ABBREVIATION,
    WARRIORS_FULL_NAME: WARRIORS_ABBREVIATION,
    ROCKETS_FULL_NAME: ROCKETS_ABBREVIATION,
    PACERS_FULL_NAME: PACERS_ABBREVIATION,
    CLIPPERS_FULL_NAME: CLIPPERS_ABBREVIATION,
    LAKERS_FULL_NAME: LAKERS_ABBREVIATION,
    GRIZZLIES_FULL_NAME: GRIZZLIES_ABBREVIATION,
    HEAT_FULL_NAME: HEAT_ABBREVIATION,
    BUCKS_FULL_NAME: BUCKS_ABBREVIATION,
    TIMBERWOLVES_FULL_NAME: TIMBERWOLVES_ABBREVIATION,
    PELICANS_FULL_NAME: PELICANS_ABBREVIATION,
    KNICKS_FULL_NAME: KNICKS_ABBREVIATION,
    THUNDER_FULL_NAME: THUNDER_ABBREVIATION,
    MAGIC_FULL_NAME: MAGIC_ABBREVIATION,
    SIXERS_FULL_NAME: SIXERS_ABBREVIATION,
    SUNS_FULL_NAME: SUNS_ABBREVIATION,
    BLAZERS_FULL_NAME: BLAZERS_ABBREVIATION,
    KINGS_FULL_NAME: KINGS_ABBREVIATION,
    SPURS_FULL_NAME: SPURS_ABBREVIATION,
    RAPTORS_FULL_NAME: RAPTORS_ABBREVIATION,
    JAZZ_FULL_NAME: JAZZ_ABBREVIATION,
    WIZARDS_FULL_NAME: WIZARDS_ABBREVIATION
}
