name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.DO_DROPLET_IP }}

    - name: Deploy code to DigitalOcean
      run: |
        ssh root@${{ secrets.DO_DROPLET_IP }} "cd ~/nba_projections_scraper && git pull origin main"
