name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DROPLET_HOST_KEY }}

      - name: Deploy code to DigitalOcean
        run: |
          ssh root@${{ secrets.DROPLET_IP }} "
            cd ~/../home/lyonvv/nba_projections_scraper &&
            git pull origin main &&
            cd projections_scraper &&
            source env/bin/activate &&
            pip install -r requirements.txt &&
            echo 'Updating .env file' &&
            echo 'GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}' > .env
          "
