name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 18 * * *" # 1 PM EST (18:00 UTC) every day

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DROPLET_HOST_KEY }}

      - name: Copy data files from DigitalOcean
        run: |
          # Create a directory to store data files
          mkdir -p ./website/data

          # Use SCP to securely copy files from the droplet
          # Replace '/path/to/source/files/' with the actual path to your data files on the droplet
          scp -r root@${{ secrets.DROPLET_IP }}:/mnt/external/projections/ ./website/data/

          ls ./website/data

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: |
            website/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('website/package-lock.json', 'website/**/*.js', 'website/**/*.jsx', 'website/**/*.ts', 'website/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('website/package-lock.json') }}

      - name: Install dependencies
        run: |
          cd website
          npm install

      - name: Build and export Next.js app
        run: |
          cd website
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch where the site will be deployed
          folder: out # The folder with the static files (by default `out`)
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
