name: Deploy Next.js
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 18 * * *" # 1 PM EST (18:00 UTC) every day

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DROPLET_HOST_KEY }}

      - name: Copy data files from DigitalOcean
        run: |
          # Create a directory to store data files
          mkdir -p ./website/data

          # Use SCP to securely copy files from the droplet
          # Replace '/path/to/source/files/' with the actual path to your data files on the droplet
          scp -r root@${{ secrets.DROPLET_IP }}:/mnt/external/projections/* ./website/data/

          ls -l ./website/data

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd website
          npm install

      - name: Build and export Next.js app
        run: |
          cd website
          npx vercel build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd website
          npx vercel --prod --yes --prebuilt --token $VERCEL_TOKEN
